info:
    name: "Benjamin Bow Tie"
    version: "1.0"
    date: 20170929
    description: "Benjamin is a bow tie pattern with four different shape options. The shape of the ends and size of the bow can be changed."
    handle: "benjamin"
    author: "WouterVdub"
    email: ""
    company: "freesewing.org"
    tags:
        - menswear
        - womenswear
        - accessory
        
parts:
    bowTie1: "Bow Tie knot"
    bowTie2: "Bow Tie knot"
    bowTie3: "Bow Tie knot"
    collarBand: "Collar band"
    

measurements:
        neckCircumference: 394
        
options:
    collarEase:
        title: "Collar ease"
        description: "The amount of ease in the collar of your shirts"
        group: "ease"
        type: "measure"
        min: 0
        max: 40
        default: 15

    tipWidth:
        title: "Tip width"
        description: "The width of the wings of the bow tie at the tip."
        group: "style"
        type: measure
        min: 24
        max: 80
        default: 65
        dependsOn: bowStyle
        onlyOn: [1,2,4]
    knotWidth:
        title: "Knot width"
        description: "The width of the bow tie at the knot/middle."
        group: "style"
        type: measure
        min: 24
        max: 40
        default: 30
    bowLength:
        title: "Bow length"
        description: "The length of the wings of the bow tie."
        group: "style"
        type: measure
        min: 100
        max: 140
        default: 120
    
    bowStyle:
        title: "Bow style"
        description: "The style of the bow"
        group: "style"
        type: "chooseOne"
        options:
            1: "Butterfly"
            2: "Diamond"
            3: "Square"
            4: "Wide Square"
        default: 2
    endStyle:
        title: "End style"
        description: "The style of the end of the tie"
        group: "style"
        type: "chooseOne"
        options:
            0: "Straight end"
            1: "Pointed end"
            2: "Rounded end"
        default: 0
        
    adjustmentRibbon:
        title: "Adjustment Ribbon"
        description: "Add a ribbon to make the tie adjustable"
        group: "sewing"
        type: "chooseOne"
        options:
            0: "None"
            1: "13½\" - 18\""
#            2: "13½\" - 20\""
        default: 0

#    sa:
#        title: "Seam Allowance"
#        description: "sa"
#        group: "sewing"
#        type: "measure"
#        min: 0
#        max: 25
#        default: 6
