info:
  name:     "Tamiko Top"
  description: "Tamiko is a zero-waste top."
  handle: "tamiko"
  level: 2
  tags:
      - womenswear
      - menswear
      - top

parts:
  top:   "Tamiko Top"

languages:
    en: English
    nl: Nederlands

measurements:
    shoulderToShoulder: 380
    chestCircumference: 1050
    centerBackNeckToWaist: 365
    naturalWaistToHip: 260

options:
    lengthBonus:
        title: "Length bonus"
        description: "The amount to lengthen the garment. A negative value will shorten it."
        group: "style"
        type: "measure"
        min: -150
        max: 350
        default: 0
