info:
  name:     "Shin Swim Trunks"
  description: "Shin is a close-fitting swim trunk pattern for men."
  handle:   "shin"
  level: 4
  tags:
      - accessories
      - sportswear

parts:
  front:   "Front"
  back:  "Back"
  waistband:  "Waistband"

languages:
    en: English

measurements:
    hipsCircumference: 970
    upperLegCircumference: 600
    hipsToUpperLeg: 220

options:
    elasticWidth:
        title: "Elastic width"
        description: "Width of the elastic band you intend to use."
        group: "fit"
        type: "measure"
        min: 15
        max: 60
        default: 35
    stretch:
        title: "Stretch"
        description: "The amount of negative ease."
        group: "fit"
        type: "percent"
        min: 5
        max: 25
        default: 15
    bulge:
        title: "Bulge"
        description: "Create some extra room in the front."
        group: "fit"
        type: "percent"
        min: 0
        max: 5
        default: 2.5
    legReduction:
        title: "Leg reduction"
        description: "Further increases negative ease at the legs to avoid gaping."
        group: "fit"
        type: "percent"
        min: 0
        max: 20
        default: 15
